name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      ORG_ID: ${{ secrets.ORG_ID }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build

    # 如果未配置必需机密，则跳过部署并提示
    - name: Skip deploy (missing secrets)
      if: ${{ env.VERCEL_TOKEN == '' || env.ORG_ID == '' || env.PROJECT_ID == '' }}
      run: |
        echo "::warning::Missing Vercel secrets (VERCEL_TOKEN / ORG_ID / PROJECT_ID). Skipping deploy."
        echo "Set them in GitHub → Settings → Secrets and variables → Actions."
      
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      if: ${{ env.VERCEL_TOKEN != '' && env.ORG_ID != '' && env.PROJECT_ID != '' }}
      with:
        vercel-token: ${{ env.VERCEL_TOKEN }}
        vercel-org-id: ${{ env.ORG_ID }}
        vercel-project-id: ${{ env.PROJECT_ID }}
        vercel-args: '--prod'